
- name: delete old repository
  command: rm {{ apt_source_dir }}/*elasticsearch*.list
  args:
    warn: no
  register: remove

- name: remove old ES
  apt: name=elasticsearch state=absent
  when: (remove|success)

- debug: msg="Removing ES old plugins"

- name: Remove AWS plugin for ES
  command: /usr/share/elasticsearch/bin/plugin remove elasticsearch/elasticsearch-cloud-aws
  tags: plugins

- name: Remove kopf monitoring in clients
  command: /usr/share/elasticsearch/bin/plugin remove lmenezes/elasticsearch-kopf
  tags: plugins
